# Generated by Django 3.1.2 on 2020-10-18 10:18

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('logo', models.ImageField(blank=True, upload_to=courses.models.get_upload_path)),
                ('subject', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'course',
                'ordering': ('owner',),
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('finished', 'FINISHED')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'homework',
                'ordering': ('lecture',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headshot', models.ImageField(blank=True, upload_to=courses.models.get_upload_path)),
                ('role', models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER')], default='student', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participant',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='courses.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='courses.participant')),
            ],
            options={
                'db_table': 'mark',
                'ordering': ('homework',),
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=256)),
                ('document', models.FileField(blank=True, upload_to=courses.models.get_upload_path_doc)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.course')),
            ],
            options={
                'db_table': 'lecture',
                'ordering': ('course',),
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='courses.lecture'),
        ),
        migrations.CreateModel(
            name='CourseParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_participant', to='courses.participant')),
            ],
            options={
                'db_table': 'course_participant',
                'ordering': ('participant',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='courses.participant'),
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='courses.mark')),
            ],
            options={
                'db_table': 'Commentary',
                'ordering': ('mark',),
            },
        ),
    ]
