# Generated by Django 3.1.2 on 2020-11-22 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentary',
            new_name='LectureCommentary',
        ),
        migrations.AlterModelOptions(
            name='lecturecommentary',
            options={'ordering': ('lecture',)},
        ),
        migrations.RemoveField(
            model_name='lecturecommentary',
            name='mark',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('finished', 'FINISHED')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='status_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturecommentary',
            name='lecture',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='courses.lecture'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='lecturecommentary',
            table='LectureCommentary',
        ),
        migrations.CreateModel(
            name='MarkCommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='courses.mark')),
            ],
            options={
                'db_table': 'MarkCommentary',
                'ordering': ('mark',),
            },
        ),
    ]
